const listData = [
  {
    amenities: "Furnished",
    image: "img1.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img2.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tangerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img3.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img4.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img5.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img6.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img7.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img8.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
  {
    amenities: "Furnished",
    image: "img9.png",
    price: "Rp.9.000.000",
    rent: "Year",
    property: "3 Beds, 2 Bats, 1,800 sqft",
    addres: "Tanggerang Selatan, Pondok Aren",
  },
];

export default listData;
